# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2021-2023, ByteDance Ltd. and/or its Affiliates
# Author: Yuanhan Liu <liuyuanhan.131@bytedance.com>

SRCS := tperf.c
SRCS += client.c
SRCS += server.c
SRCS += test.c
SRCS += conn.c
SRCS += integrity.c
SRCS += options.c
SRCS += utils.c
SRCS += mbuf.c
SRCS += event.c
SRCS += stats.c

APP  := tperf

include ../app.mk
