# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2021-2023, ByteDance Ltd. and/or its Affiliates
# Author: Yuanhan Liu <liuyuanhan.131@bytedance.com>

SRCS := sock-list-parser.c
SCRIPTS := sock-list

APP := sock-list-parser

include ../tools.mk
