# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2021-2023, ByteDance Ltd. and/or its Affiliates
# Author: Yuanhan Liu <liuyuanhan.131@bytedance.com>

SRCS := sock-trace-parser.c
SCRIPTS := sock-trace

APP := sock-trace-parser

include ../tools.mk
